
<div>
    <h2 class="review-title"><span>Reviews</span></h2>
</div>
<div class="general">
    <div class="overall">
      <?php  $summary=$this->getProduct()->getRatingSummary()->getRatingSummary();?>
      <?php  $n = round($summary / 10/2 );$m=5-$n?>
        <div class="start">
            <?php for($i=0;$i<$n;$i++):?><span class="rating iconfont icon-wujiaoxing"></span><?php endfor;?><?php for($i=0;$i<$m;$i++):?><span class="rating iconfont icon-wujiaoxing" style="color:#ccc;"></span><?php endfor;?>
        </div>

        <div class="number"><sup><?php echo $n?></sup> / <sub>5</sub></div>
        <div><button><span>Write Review</span></button></div>
    </div>
    <div class="options-list">
        <ul>
            <?php foreach($this->getRatings() as $rating):?>
                <li>
                    <dl class="dl-horizontal">
                        <dt><?php echo $rating['rating_code']?></dt>
                        <dd>
                            <span class="start"><?php  $n=round($rating['result'] / $rating['count'] / 0.2 );$m=5-$n; ?> <?php for($i=0;$i<$n;$i++):?><span class="rating iconfont icon-wujiaoxing"></span><?php endfor;?><?php for($i=0;$i<$m;$i++):?><span class="rating iconfont icon-wujiaoxing" style="color:#ccc;"></span><?php endfor;?></span>
                            <span class="person">
                            <?php $persion = round($rating['result'] / $rating['count'],2) * 100 ?>
                                <em><?php echo $persion?>%</em><progress value="<?php echo $persion?>" max="100"></progress>
                            </span>
                            <span class="result"><?php echo $rating['result']?></span>
                        </dd>
                    </dl>

                <li>
            <?php endforeach;?>
        </ul>

    </div>
</div>
<div class="write hidden">
    <?php echo $this->getChildHtml('review_form') ?>
</div>


<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)):?>
        <h2><span><?php echo $this->__('Customer Reviews') ?></span></h2>
        <?php echo $this->getChildHtml('toolbar') ?>
        <dl class="dl-horizontal">
        <?php foreach ($_items as $_review):?>
            <dt>
                <p><?php echo $this->escapeHtml($_review->getTitle()) ?></p>
            <p>
                <?php echo $this->__('Review by <span>%s</span>', $this->escapeHtml($_review->getNickname())) ?>
            </p>
            </dt>
            <dd>
                <?php $_votes = $_review->getRatingVotes(); ?>
                <?php if (count($_votes)): ?>
                <table class="ratings-table">
                    <col width="1" />
                    <col />
                    <tbody>
                        <?php foreach ($_votes as $_vote): ?>
                        <tr>
                            <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                            <td>
                                <div class="rating-box">
                                    <?php  $summary= $_vote->getPercent();?>
                                    <?php  $n = round($summary / 10/2 );$m=5-$n?>
                                    <div class="rating">
                                        <?php for($i=0;$i<$n;$i++):?><span class="rating iconfont icon-wujiaoxing"></span><?php endfor;?><?php for($i=0;$i<$m;$i++):?><span class="rating iconfont icon-wujiaoxing" style="color:#ccc;"></span><?php endfor;?>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif; ?>
                <?php echo nl2br($this->escapeHtml($_review->getDetail())) ?>
                <small class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
            </dd>
        <?php endforeach; ?>
        </dl>
        <?php echo $this->getChildHtml('toolbar') ?>
    <?php endif;?>

</div>
