<div class="home-banner">
    <div class="texts">
        <div class="txt1"><p>UNCOVER,</p><p> DISCOVER</p></div>
        <div class="txt2">Your vanity will never be the same</div>
    </div>
    <div class="nav">
        <ul>
            <li><a href="">SKIN CARE</a></li>
            <li><a href="">HAIR CARE</a></li>
            <li><a href="">NATURAL</a></li>
            <li><a href="">MAKEUP</a></li>
        </ul>
    </div>
</div>

<div class="home-content">
    <div class="container">
        <div class="row">
            <div class="recommend">
                <div class="wrap">
                    <div class="name">We Recommend</div>
                </div>
                <div class="slider">

                </div>

            </div>
            <div class="now"></div>
            <div class="new"></div>
            <div class="footer-banner1"></div>
            <div class="footer-banner2"></div>
        </div>
    </div>
</div>